algoritmo "Operadores relacionais"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Função :
// Autor :
// Data : 5/29/2020
// Seção de Declarações
var
   n1, n2 : real

inicio
   // Seção de Comandos
   n1 := 10
   n2 := 15

   se(n1 <> n2) entao
      escreval("Nota 1 é diferente")
   senao
      escreval("Nota 1 não é igual")
   fimse

fimalgoritmo
