algoritmo "Operadores aritmeticos"
// Função :
// Autor :
// Data : 5/29/2020
// Seção de Declarações 
var
res, valor1, valor2, valor3: real

inicio
// Seção de Comandos
valor1 := 10
valor2 := 10
valor3 := 10
//res := (valor1 + valor2) //Soma
//res := (valor1 - valor2) //Subtracao
//res := (valor1 * valor2) //Multiplicação
//res := (valor1 / valor2) //Divisao
res := ((valor1 + valor2 + valor2) / valor3) % 2 //Resto da Divisao

escreval ("Resultado: ", res)


fimalgoritmo
